### ISSUE TITLE
Address This

### ISSUE THREAD

**Issue by k-wayne** [MoonfireSeco/strawpoll-bot#4]
It gives an error:
Traceback (most recent call last): File "script.py", line 146, in <module> prepare (args, motd) File "script.py", line 83, in prepare checkboxID = str (int (checkboxID) + opt - 1) ValueError: invalid literal for int() with base 10: ''

**Comment by Milkdrop** [comment]
Can you provide the poll URL that causes this?

**Comment by thiagolinhares** [comment]
EDIT:
Nevermind. I was trying "strawpoll.com" poll.
 -------------------------------------------------------
Here same error
```
Connecting to: https://www.strawpoll.me/y3ydprpb
Traceback (most recent call last):
  File "script.py", line 146, in <module>
    prepare (args, motd)
  File "script.py", line 83, in prepare
    checkboxID = str (int (checkboxID) + opt - 1)
ValueError: invalid literal for int() with base 10: ''

```

**Comment by Mamdouh-Aloufi** [comment]
did you fix it? so it work with the new address "strawpoll.com" ?

**Comment by thiagolinhares** [comment]
yes.
it's working fine using strawpoll.com

apparently they are two distinct services.

**Comment by Mamdouh-Aloufi** [comment]
Can you send me the edited code? I tried to change strawpoll.me with strapoll.com but it is not workin /:
