### ISSUE TITLE
urllib3.exceptions.ProxySchemeUnknown: Not supported proxy scheme xxx.xxx.xx.xx

### ISSUE THREAD

**Issue by kayraucklnc** [MoonfireSeco/strawpoll-bot#6]
Doesn't work at all

**Comment by Milkdrop** [comment]
You probably supplied a bad proxy list.

**Comment by yuval59** [comment]
Hi, I've tried either supplying the proxy list you left in your suggestions inside your code and not giving it any proxy list so the code downloads them, and I get the same exact error.
here is the full error:
`Getting proxies from an on-line source...
Loaded 402 proxies.
Connecting to: https://www.strawpoll.me/20646569
Checkbox ID: 152507346
Max threads: 16
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\yuval\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\yuval\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\yuval\Downloads\strawpoll-bot-master\script.py", line 121, in vote
    page = requests.get (url, headers = headers, proxies = proxies, timeout = 10).text
  File "C:\Users\yuval\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\yuval\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\yuval\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\yuval\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\yuval\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 412, in send
    conn = self.get_connection(request.url, proxies)
  File "C:\Users\yuval\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 309, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "C:\Users\yuval\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 193, in proxy_manager_for
    manager = self.proxy_manager[proxy] = proxy_from_url(
  File "C:\Users\yuval\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\poolmanager.py", line 492, in proxy_from_url
    return ProxyManager(proxy_url=url, **kw)
  File "C:\Users\yuval\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\poolmanager.py", line 429, in __init__
    raise ProxySchemeUnknown(proxy.scheme)
urllib3.exceptions.ProxySchemeUnknown: Not supported proxy scheme None`

**Comment by UniFrann264** [comment]
I got this error in version 3.9.1. I have tested version 3.7.5 and the proxies have worked for me.
