### ISSUE TITLE
Does it work for strawpoll.com?

### ISSUE THREAD

**Issue by husseinzaid** [MoonfireSeco/strawpoll-bot#9]
I tried this with the the following poll in  strawpoll.com : 
id: rwck5xw1x
I am getting this error : 

Traceback (most recent call last):
  File "script.py", line 153, in <module>
    prepare (args, motd)
  File "script.py", line 84, in prepare
    checkboxID = str (int (checkboxID) + opt - 1)
ValueError: invalid literal for int() with base 10: ''

Is there a solution for this ?

**Comment by Horizonik** [comment]
Same, doesn't seem to work on stawpoll.com

**Comment by rgowdame** [comment]
does it work? is there any bot which works?

**Comment by Milkdrop** [comment]
It doesn't work for strawpoll.com
